package senior.erp.utils;

public class SelectsAGRO {

public SelectsAGRO() {
	
}

public static final String selectDocumentosGeradosRecebimentoGraos= 
"SELECT\r\n" + 
"	DADOS.* \r\n" + 
"FROM\r\n" + 
"	(SELECT	E115CES.CODEMP, E115CES.CODFIL, E115CES.DATENT, E115CES.SEQENT, E115CES.NUMTIC,\r\n" + 
"			E115CES.SITCES, E115CES.PESENI, E115CES.PESSAI,\r\n" + 
"			((E115CES.PESENI - E115CES.PESSAI)-\r\n" + 
"				(SELECT COALESCE(SUM( E115ICL.QTDDSC ),0) AS QTD\r\n" + 
"				 FROM E115ICL\r\n" + 
"				 WHERE E115ICL.CODEMP = E115CES.CODEMP\r\n" + 
"				 AND E115ICL.CODFIL = E115CES.CODFIL\r\n" + 
"				 AND E115ICL.DATENT = E115CES.DATENT\r\n" + 
"				 AND E115ICL.SEQENT = E115CES.SEQENT\r\n" + 
"				 AND E115ICL.CODICL <> 3)) AS QTDFIMPESAGEM,\r\n" + 
"			(SELECT COALESCE(SUM( E115PFO.QTDPFO ),0) AS QTD\r\n" + 
"			 FROM E115PFO\r\n" + 
"			 WHERE E115PFO.CODEMP = E115CES.CODEMP\r\n" + 
"			 AND E115PFO.CODFIL = E115CES.CODFIL\r\n" + 
"			 AND E115PFO.DATENT = E115CES.DATENT\r\n" + 
"			 AND E115PFO.SEQENT = E115CES.SEQENT) AS QTDPARTICIPANTES,\r\n" + 
"			(SELECT SUM( E420IPO.QTDORI - E420IPO.QTDCAN ) AS QTD\r\n" + 
"			 FROM E420IPO\r\n" + 
"			 WHERE E420IPO.CODEMP = E115CES.CODEMP\r\n" + 
"			 AND E420IPO.FILCES = E115CES.CODFIL\r\n" + 
"			 AND E420IPO.DATCES = E115CES.DATENT\r\n" + 
"			 AND E420IPO.SEQCES = E115CES.SEQENT\r\n" + 
"			 AND E420IPO.SEQIOR = 0) AS QTDORDEMCOMPRA,\r\n" + 
"			(\r\n" + 
"			    (SELECT COALESCE(SUM(NOTADEPOSITO.QTDREC),0) \r\n" + 
"			    FROM E115CES E115CES_2\r\n" + 
"				LEFT JOIN(SELECT DISTINCT E115CES_3.CODEMP, E115CES_3.CODFIL, E115CES_3.DATENT,\r\n" + 
"							E115CES_3.SEQENT, E440IPC.NUMNFC, E440IPC.SEQIPC, E440IPC.QTDREC\r\n" + 
"						FROM E115CES E115CES_3, E420IPO E420IPO_2, E440NFC, E440IPC\r\n" + 
"						WHERE(0=0)\r\n" + 
"							AND E420IPO_2.CODEMP = E115CES_3.CODEMP\r\n" + 
"							AND E420IPO_2.FILCES = E115CES_3.CODFIL\r\n" + 
"							AND E420IPO_2.DATCES = E115CES_3.DATENT\r\n" + 
"							AND E420IPO_2.SEQCES = E115CES_3.SEQENT\r\n" + 
"							AND E440NFC.CODEMP = E420IPO_2.CODEMP\r\n" + 
"							AND E440NFC.FILOCP = E420IPO_2.CODFIL\r\n" + 
"							AND E440NFC.NUMOCP = E420IPO_2.NUMOCP\r\n" + 
"							AND E440IPC.CODEMP = E440NFC.CODEMP\r\n" + 
"							AND E440IPC.CODFIL = E440NFC.CODFIL\r\n" + 
"							AND E440IPC.NUMNFC = E440NFC.NUMNFC\r\n" + 
"							AND E440IPC.CODFOR = E440NFC.CODFOR\r\n" + 
"							AND E440IPC.CODSNF = E440NFC.CODSNF) NOTADEPOSITO 	\r\n" + 
"				ON (NOTADEPOSITO.CODEMP = E115CES_2.CODEMP)\r\n" + 
"				AND(NOTADEPOSITO.CODFIL = E115CES_2.CODFIL)\r\n" + 
"				AND(NOTADEPOSITO.DATENT = E115CES_2.DATENT)\r\n" + 
"				AND(NOTADEPOSITO.SEQENT = E115CES_2.SEQENT)		\r\n" + 
"								\r\n" + 
"				WHERE E115CES_2.CODEMP = E115CES.CODEMP\r\n" + 
"				AND E115CES_2.CODFIL = E115CES.CODFIL\r\n" + 
"				AND E115CES_2.DATENT = E115CES.DATENT\r\n" + 
"				AND E115CES_2.SEQENT = E115CES.SEQENT)\r\n" + 
"				\r\n" + 
"				+\r\n" + 
"				\r\n" + 
"				((SELECT COALESCE(SUM(NOTASCOMPRAIMEDIATA.QTDREC),0) \r\n" + 
"			    FROM E115CES E115CES_4\r\n" + 
"				LEFT JOIN(SELECT DISTINCT E115CES_5.CODEMP, E115CES_5.CODFIL, E115CES_5.DATENT,\r\n" + 
"				            	E115CES_5.SEQENT, E440IPC.NUMNFC, E440IPC.SEQIPC, E440IPC.QTDREC\r\n" + 
"						  FROM E115CES E115CES_5, E420IPO E420IPO_3, E440IPC\r\n" + 
"						  WHERE(0=0)\r\n" + 
"						  AND E420IPO_3.CODEMP = E115CES_5.CODEMP\r\n" + 
"						  AND E420IPO_3.FILCES = E115CES_5.CODFIL\r\n" + 
"						  AND E420IPO_3.DATCES = E115CES_5.DATENT\r\n" + 
"						  AND E420IPO_3.SEQCES = E115CES_5.SEQENT\r\n" + 
"						  AND E440IPC.CODEMP = E420IPO_3.CODEMP\r\n" + 
"						  AND E440IPC.FILOCP = E420IPO_3.CODFIL\r\n" + 
"						  AND E440IPC.NUMOCP = E420IPO_3.NUMOCP) NOTASCOMPRAIMEDIATA 	\r\n" + 
"				ON (NOTASCOMPRAIMEDIATA.CODEMP = E115CES_4.CODEMP)\r\n" + 
"				AND(NOTASCOMPRAIMEDIATA.CODFIL = E115CES_4.CODFIL)\r\n" + 
"				AND(NOTASCOMPRAIMEDIATA.DATENT = E115CES_4.DATENT)\r\n" + 
"				AND(NOTASCOMPRAIMEDIATA.SEQENT = E115CES_4.SEQENT)\r\n" + 
"				WHERE E115CES_4.CODEMP = E115CES.CODEMP\r\n" + 
"				AND E115CES_4.CODFIL = E115CES.CODFIL\r\n" + 
"				AND E115CES_4.DATENT = E115CES.DATENT\r\n" + 
"				AND E115CES_4.SEQENT = E115CES.SEQENT))\r\n" + 
"				\r\n" + 
"				) AS QTDEMNOTASFISCAIS\r\n" + 
"	FROM E115CES\r\n" + 
"	WHERE E115CES.CODEMP = ?\r\n" + 
"	AND E115CES.CODFIL = ?\r\n" + 
"	AND E115CES.DATENT = ?\r\n" + 
"	AND E115CES.SEQENT = ?\r\n" + 
"	AND E115CES.ORICES = 5) DADOS\r\n" + 
"	\r\n" + 
"ORDER BY DADOS.DATENT, DADOS.CODFIL, DADOS.SEQENT";

public static final int CODEMP = 0;
public static final int CODFIL = 1;
public static final int DATENT = 2;
public static final int SEQENT = 3;
public static final int NUMTIC = 4;
public static final int SITCES = 5;
public static final int PESENI = 6;
public static final int PESSAI = 7;
public static final int QTDFIMPESAGEM = 8;
public static final int QTDPARTICIPANTES = 9;
public static final int QTDORDEMCOMPRA = 10;
public static final int QTDNOTASFISCAIS = 11;

}

